import type { ModelProfile, ReferenceRole } from "../src/types.js";

const updatedAt = "2026-08-27T00:00:00.000Z";
const priority: ReferenceRole[] = [
  "IDENTITY", "WARDROBE", "CREATURE", "ANIMAL", "LOCATION", "PROP",
  "START_FRAME", "END_FRAME", "VIDEO_CONTINUITY", "COMPOSITION", "CAMERA",
  "MOTION", "LIGHTING", "STYLE", "VOICE", "AUDIO",
];

export const createDefaultModelProfiles = (): ModelProfile[] => [
  {
    id: "seedance-2.5",
    provider: "seedance",
    model: "seedance-2.5",
    displayName: "Seedance 2.5",
    enabled: true,
    maxDurationSeconds: 30,
    maxImageReferences: 30,
    maxVideoReferences: 10,
    maxAudioReferences: 10,
    supportsStartFrame: true,
    supportsEndFrame: true,
    supportsReferenceTags: true,
    tagTemplate: "@Image {position}",
    rolePriority: [...priority],
    notes: ["Official public Seedance 2.5 product profile; edit this project profile if the selected endpoint differs."],
    updatedAt,
  },
  {
    id: "minimax-s2v-01",
    provider: "minimax",
    model: "S2V-01",
    displayName: "MiniMax S2V-01",
    enabled: true,
    maxImageReferences: 1,
    supportsStartFrame: false,
    supportsEndFrame: false,
    supportsReferenceTags: false,
    tagTemplate: "Reference image {position}",
    rolePriority: [...priority],
    notes: ["S2V-01 is a single-subject reference profile. Identity is never silently removed when the limit is exceeded."],
    updatedAt,
  },
  {
    id: "higgsfield",
    provider: "higgsfield",
    model: "provider-selected",
    displayName: "Higgsfield (editable model)",
    enabled: true,
    supportsStartFrame: true,
    supportsEndFrame: true,
    supportsReferenceTags: true,
    tagTemplate: "Reference {position}",
    rolePriority: [...priority],
    notes: ["Limits intentionally unset because Higgsfield exposes multiple models. Configure the selected model before a paid job."],
    updatedAt,
  },
  {
    id: "generic",
    provider: "generic",
    model: "generic",
    displayName: "Generic structured prompt",
    enabled: true,
    supportsStartFrame: true,
    supportsEndFrame: true,
    supportsReferenceTags: true,
    tagTemplate: "REF_{position}",
    rolePriority: [...priority],
    notes: ["No provider limits are assumed."],
    updatedAt,
  },
];
